### ISSUE TITLE
Luis.AI unable to access Luis Applications from dashboard

### ISSUE THREAD

**Issue by aatifjiwani** [microsoft/botframework-sdk#5460]
I am trying to access my apps from the dashboard but I am consistently getting this server error: 

`
ERROR 0: A server error occured. Please refresh the page and try again.
    at e.handle (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1469228)
    at e.t._delegate (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1468177)
    at e.handle (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1468810)
    at e.t._delegate (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1468177)
    at e.handle (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1468395)
    at t.handle (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1469032)
    at e.selector (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1469561)
    at e.error (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:166442)
    at e.notifyError (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:813758)
    at e._error (https://www.luis.ai/main.758bfdb488ea36631d4a.js:1:1952581)
`

Here is a screenshot:

![image](https://user-images.githubusercontent.com/34924102/61160286-c30cad80-a4b3-11e9-92a2-9fffee060ad4.png)

All I did was sign into Luis.ai and the dashboard always shows "loading apps..."

Please fix, I am creating a chatbot that needs to use these resources now

**Comment by aatifjiwani** [comment]
![image](https://user-images.githubusercontent.com/34924102/61161704-eaff0f80-a4b9-11e9-8a35-f994f237d6dc.png)

I believe the issue is this ^. It is not able to find my apps because it cannot find the API endpoint.

**Comment by aatifjiwani** [comment]
seems to be fixed.
