### ISSUE TITLE
Latest sdk 4.5.4 gives error when debugging locally

### ISSUE THREAD

**Issue by neetgupta7** [microsoft/botframework-sdk#5635]
I upgraded Microsoft.Bot.Builder.Skills to 4.5.4 and now when i debug my skill locally with simple echo dialog with blank microsoftAppId and password i get below error.

### System.ArgumentNullException: Value cannot be null.
Parameter name: microsoftAppId
   at Microsoft.Bot.Builder.Skills.Auth.MsJWTAuthenticationProvider..ctor(String microsoftAppId, String openIdMetadataUrl) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Auth\MsJWTAuthenticationProvider.cs:line 20
   at Microsoft.Bot.Builder.Skills.SkillWebSocketAdapter..ctor(SkillWebSocketBotAdapter skillWebSocketBotAdapter, BotSettingsBase botSettingsBase, IWhitelistAuthenticationProvider whitelistAuthenticationProvider, IBotTelemetryClient botTelemetryClient) in D:\a\1\s\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\SkillWebSocketAdapter.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetrySaveBodyASPMiddleware.Invoke(HttpContext httpContext) in d:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.ApplicationInsights.Core\TelemetrySaveBodyASPMiddleware.cs:line 55
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by cleemullins** [comment]
@neetgupta7 Thanks for reporting this. I've engaged the engineer driving the recent security changes, as well as our support engineers. Please be aware that both Web Sockets and Skills are currently not officially supported (beta's), but we'll try to get this resolved ASAP.
