### ISSUE TITLE
Failed to decrypt conversation id for format *==@p2p.thread.skype

### ISSUE THREAD

**Issue by huyjack178** [microsoft/botframework-sdk#6133]
Hi, currently, our old skype group has id with this format 19:I3RyYW5jaHVvbmc4Mi8kYW5ocGRfYnM7MzZjNzE3ZjFjMjI4YWI4MA==@p2p.thread.skype

And when send via bot framework, I got this Failed to decrypt conversation id error in portal
Can you help me solve this problem?
![image](https://user-images.githubusercontent.com/11793001/101130022-498bd700-3635-11eb-8444-fcf1cd983258.png)

**Comment by hcyang** [comment]
Hi @EricDahlvang, any updaet?

**Comment by EricDahlvang** [comment]
Please share the stack trace for the error.

What code is sending the message? Is this a recent error on an existing bot? What does 'old skype group id" refer to from the perspective of the bot?

Unfortunately,  the skype channel has been deprecated. As far as i know, existing bots should still function. But i need to check on this.

**Comment by huyjack178** [comment]
Hi @EricDahlvang, here you are 
```
Operation returned an invalid status code 'BadRequest'
   at Microsoft.Bot.Connector.Conversations.SendToConversationWithHttpMessagesAsync(String conversationId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.SendToConversationAsync(IConversations operations, String conversationId, Activity activity, CancellationToken cancellationToken)
   at Fanex.Bot.Skynex._Shared.MessageSenders.SkypeConversation.SendAsync(MessageInfo messageInfo) in D:\Builds\UnCompiled\NEXOPS\Bot\Fanex.Bot\src\bots\Fanex.Bot.Skynex\_Shared\MessageSenders\SkypeConversation.cs:line 55
   at Fanex.Bot.Skynex._Shared.MessageSenders.Conversation.ForwardMessage(MessageInfo messageInfo) in D:\Builds\UnCompiled\NEXOPS\Bot\Fanex.Bot\src\bots\Fanex.Bot.Skynex\_Shared\MessageSenders\Conversation.cs:line 116
```

**Comment by EricDahlvang** [comment]
Is this an existing bot, with a new exception?  Did sending this same message in the same way work before, but now does not?  Is it every time you send a message?  Are you using a new bot to send to this group conversation?

If this exception is new, when did it first appear?  Please elaborate more regarding the circumstances and history behind this error.

(transferring this issue to the services repository)
