### ISSUE TITLE
Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by RajdeepRay0411** [microsoft/botframework-sdk#6154]
## Version
SDK Platform: .NET Core 3.1
SDK Version: 4.8.0
Active Channel: MSTeams
Deployment Environment: Azure bot Service/localhost

## Describe the bug
when I am using "var data= await turnContext.SendActivityAsync(replyActivity)". The exception is coming as one of them in **Default Adapter**: "Operation returned an invalid status code 'NotFound'", "Operation returned an invalid status code 'Forbidden'" and "Operation returned an invalid status code 'BadRequest'".

## Exception StackTrace

```
     at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
     at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
     at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
     at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass25_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.<>c__DisplayClass7_0.<<OnTurnAsync>b__0>d.MoveNext()  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
     at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken)
     at AIP_BotEngine_Implementation.Adapters.DefaultAdapter.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\a\1\s\BotEnginev2\AIP.BotEngine.Implementations\AIP_BotEngine_Implementation\AIP_BotEngine_Implementation\Adapters\DefaultAdapter.cs:line 78
```

**Comment by RajdeepRay0411** [comment]
Hi @jwiley84, are there any updates on this issue?

**Comment by tracyboehrer** [comment]
@RajdeepRay0411 Have you tried to reproduce this on a newer SDK version?  The latest is 4.11

**Comment by LeeParrishMSFT** [comment]
Closing for inactivity.
