### ISSUE TITLE
Conversation state unavailable error when adding Composer Dialogs in Virtual Assistant Template 

### ISSUE THREAD

**Issue by RajdeepRay0411** [microsoft/botframework-sdk#6156]
## Version
SDK runtime packages: 4.11.1

## Describe the bug
When I am trying to connect composer dialogs in my Virtual assistant template then I am getting an error in the **Default Adapter** class which in turn is getting triggered from Dialog Bot(Main Bot Constructor) on line

```c#
await _dialogManager.OnTurnAsync(turnContext, cancellationToken: cancellationToken);
```

## Exception Message
Unable to get an instance of ConversationState from turnContext.

## Exception Stack Trace

```
at Microsoft.Bot.Builder.Dialogs.DialogManager.OnTurnAsync(ITurnContext context, CancellationToken cancellationToken)
at AIP.BotEngine.Implementations.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\UnaBOT\BotEnginev2\AIP.BotEngine.Implementations\AIP_BotEngine_Implementation\AIP_BotEngine_Implementation\Bots\DialogBot.cs:line 85
at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
```

**Comment by v-kydela** [comment]
Thank you for the report, @RajdeepRay0411

You can see in the [adaptive dialogs samples](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/adaptive-dialog/01.multi-turn-prompt/AdapterWithErrorHandler.cs#L25) that the conversation state is made available using the [`UseBotState`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/AdapterExtensions.cs#L27-L52) extension method. I don't know why this isn't happening in your case because I don't have your code. Please provide the following:

1. Repro steps
2. Screenshots
2. Links to any samples or documentation you've followed

**Comment by RajdeepRay0411** [comment]
Hi @v-kydela, the issue is a duplicate of "**Conversation state unavailable error when adding Twilio/ Infobip service integration** "- where the user is trying to integrate with Twilio adaptor but I am trying to integrate composer dialogs with a virtual assistant for teams cannel but facing the same issue as his.

**Comment by v-kydela** [comment]
Hi @RajdeepRay0411 

I'm sorry but that information doesn't help me because no solution or explanation was given in that other issue. Are you willing to provide the information I asked for?

**Comment by v-kydela** [comment]
@RajdeepRay0411 - Are you still working on this?

**Comment by LeeParrishMSFT** [comment]
Closing for inactivity.

**Comment by Clooney24** [comment]
this helped me solve that issue: [https://stackoverflow.com/questions/66498624/bot-framework-composer-slack-adapter-unhandled-error-unable-to-get-an-instanc](url)
