### ISSUE TITLE
An unhandled exception has occurred while executing the request. System.Net.Http.HttpRequestException: Address not available

### ISSUE THREAD

**Issue by parsalotfy** [microsoft/botframework-sdk#6285]
## Version
What package version of the SDK are you using.

I use this container as build environment : **mcr.microsoft.com/dotnet/sdk:3.1-alpine** 
on Windows 10 OS build 19043.964
and use Bot framework emulator version 4.13 to test on windows.

## Describe the bug
Give a clear and concise description of what the bug is.

When I run an emptybot in an alpine container, and test it with bot framework emulator, this error happens :

```
/mybot # dotnet run --urls http://0.0.0.0:80
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /mybot
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:8080/api/messages application/json 625
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'EmptyBot.Controllers.BotController.PostAsync (mybot)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Bot"}. Executing controller action with signature System.Threading.Tasks.Task PostAsync() on controller EmptyBot.Controllers.BotController (mybot).
info: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      Received an incoming activity.  ActivityId: f506fe20-b123-11eb-8956-b3b98984e597
info: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      Sending activity.  ReplyToId: f506fe20-b123-11eb-8956-b3b98984e597
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action EmptyBot.Controllers.BotController.PostAsync (mybot) in 550.7759ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'EmptyBot.Controllers.BotController.PostAsync (mybot)'


fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: Address not available
 ---> System.Net.Sockets.SocketException (99): Address not available
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)


   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at EmptyBot.EmptyBot.OnMembersAddedAsync(IList`1 membersAdded, ITurnContext`1 turnContext, CancellationToken cancellationToken) in /mybot/EmptyBot.cs:line 22
   at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(ClaimsIdentity claimsIdentity, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpResponse, IBot bot, CancellationToken cancellationToken)
   at EmptyBot.Controllers.BotController.PostAsync() in /mybot/Controllers/BotController.cs:line 34
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 704.1886ms 500 text/plain
```

and in emulator this error is shown : `POST 500 directline/conversations/<conversationId>/activities`

## To Reproduce
1. `sudo docker pull mcr.microsoft.com/dotnet/sdk:3.1-alpine`
2. `docker run --rm -it -p 8080:80  mcr.microsoft.com/dotnet/sdk:3.1-alpine sh`
3. `mkdir mybot`
4. `cd mybot`
5. `dotnet new -i Microsoft.Bot.Framework.CSharp.EmptyBot`
6. `dotnet new emptybot`
7. `dotnet run --urls http://0.0.0.0:80`
8. Go to bot framework emulator 
9. Open bot on this url : `http://localhost:8080/api/messages`
10. Look at the error and pull your hair.

## Expected behavior
Give a clear and concise description of what you expected to happen.

When I do not use an alpine container and run an empty bot in windows, it works as expected and sends me a welcome message in emulator.

Running in alpine container should behave similarly, bot it doesn't.

## Screenshots

![image](https://user-images.githubusercontent.com/30390810/117591442-c7ef2680-b149-11eb-9c72-f9ea927096d2.png)

## Additional context

Please help me to fix this <3
## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by jwiley84** [comment]
on it!

**Comment by parsalotfy** [comment]
could you reproduce that error ? or that error happened just in my side ?!
sadly my project is stand by just because of this error :(

**Comment by ninggao** [comment]
@jwiley84 Any updates on this issue?

**Comment by jwiley84** [comment]
Apologies, my docker skills are a bit rusty. I should have an answer for you by this morning.

**Comment by ninggao** [comment]
@jwiley84  Any updates on this issue?

**Comment by parsalotfy** [comment]
Thank you for your efforts investigating my issue.

**Comment by jwiley84** [comment]
My apologies, this somehow fell off my radar.

**Comment by jwiley84** [comment]
My sincerest apologies. I'm having a significant difficulty getting docker to run on my computer.

**Comment by parsalotfy** [comment]
@jwiley84 Can I help?

**Comment by tdurnford** [comment]
@jwiley84 If you're having docker issues, is there another support engineer who look into this?

**Comment by anusharavindrar** [comment]
@parsalotfy, 

- I am able to reproduce the issue on my end. Here are the screenshots for the same:

![image](https://user-images.githubusercontent.com/48731427/120719791-bfa3b600-c47f-11eb-9bdf-fc0c94f20462.png)
![image](https://user-images.githubusercontent.com/48731427/120720212-8ddf1f00-c480-11eb-8df5-d548d34f3b78.png)

- However, when I configure ngrok, I am able to get the response in the emulator.

![image](https://user-images.githubusercontent.com/48731427/120720343-c121ae00-c480-11eb-9909-1af3e9a03aaa.png)
![image](https://user-images.githubusercontent.com/48731427/120720368-d0086080-c480-11eb-8d3a-bea161e51b6a.png)

**Based on the information you have provided, the bot is running in the container, whereas the Emulator is on the local machine right?** AFAIK, if the bot and the emulator are not on same local machine, then you will have to configure ngrok for the bot to respond back to the emulator. 

Investigating further.

**Comment by parsalotfy** [comment]
Sorry for late reply...
Without ngrok, it doesn't work, either in vps, or in desktop
But as you said when I configure ngrok in emulator, it works.
When I use ngrok externally, it doesn't work again!
I need to check if that works when I publish my bot and connect it completely.
I will send further information here after other tests...

**Comment by anusharavindrar** [comment]
@parsalotfy, any update on the above comment?

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to re-open if issue persists.

**Comment by parsalotfy** [comment]
I can no longer reproduce this issue.
Thank you for the fix.
