### ISSUE TITLE
Resource temporarily unavailable error while starting the conversation

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/botframework-sdk#6380]
Hello All,

I am using Azure Bot service and Bot Framework V4(4.13.2) for my Chatbot and enabled MS Teams as a channel in Bot service. I am using Orchestrator as a dispatcher for finding the score to route the request to either LUIS or QnA Maker. It is working fine in emulator and I deployed it in Linux server.

While starting the conversation (by having a gap of 1 hour or so) I am getting below error in the bot framework. And when I ping again the Chatbot, it is working fine. This error I am getting everytime I start the conversation (by having some time gap).

Also I am not getting the issue when I type a QnA Maker based query. It is working fine while starting a new conversation. I am only getting the error when I type any LUIS based query. And if i retype the same query (2 or 3 times) it works fine. There might be some timeout issue while calling the LUIS API. I am using Declarative adaptive dialog for bot framework dialogs.

fail: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0] Exception caught : Resource temporarily unavailable

Kindly help me in solving the issue. I have other chatbots integrated with Teams and using QnA Maker via bot framework. I didn't get these kind of issues over there after deployment. 

Thanks in advance for your response.

In the Issues section I saw a similar issue [(Issue)](https://github.com/microsoft/botframework-sdk/issues/2078) but that is not yet closed and no solution provided.

**Comment by Vigneshramkumar** [comment]
I am getting the error while the Dialog class calls the LUIS Recognize method. Below is the exception stack trace.

As mentioned earlier, I am getting this error only for pinging the chatbot after sometime. This error will come for some 3 to 4 times then it will start working. Not sure whether the issue is in Bot framework end.
I tried to get the LUIS response through prediction URL from LUIS portal. It is working fine always.

`Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      Exception caught : Resource temporarily unavailable        Resource temporarily unavailable           at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Rest.RetryAfterDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.AI.Luis.LuisDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.GetLuisResponseAsync(String utterance, LuisPredictionOptions options, HttpClient httpClient, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.RecognizeAsync(ITurnContext turnContext, String utterance, LuisPredictionOptions options, HttpClient httpClient, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.RecognizeInternalAsync(DialogContext dialogContext, Activity activity, HttpClient httpClient, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeInternalAsync(DialogContext dialogContext, Activity activity, LuisRecognizerOptions predictionOptions, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.AI.Luis.LuisAdaptiveRecognizer.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers.MultiLanguageRecognizer.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers.RecognizerSet.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.OnRecognizeAsync(ActionContext actionContext, Activity activity, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ProcessEventAsync(ActionContext actionContext, DialogEvent dialogEvent, Boolean preBubble, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ProcessEventAsync(ActionContext actionContext, DialogEvent dialogEvent, Boolean preBubble, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ProcessEventAsync(ActionContext actionContext, DialogEvent dialogEvent, Boolean preBubble, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.OnPreBubbleEventAsync(DialogContext dc, DialogEvent dialogEvent, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.Dialog.OnDialogEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.DialogContainer.OnDialogEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InnerRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.DialogManager.OnTurnAsync(ITurnContext context, CancellationToken cancellationToken)
         at SkillBot.Bots.ChatBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in /media/sharuk/hddntfs/Works/Beez/skill-ms-bot-framework/Bots/ChatBot.cs:line 214
         at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)   -2147467259`

**Comment by compulim** [comment]
Pinging Carol on this.

**Comment by compulim** [comment]
@Vigneshramkumar could you send us the application ID and timestamp (with time zone) of when it happened? We can look it up on our service end and see what happened.

**Comment by munozemilio** [comment]
Hello @Vigneshramkumar, we will close this due to inactivity. Feel free to reopen and provide the requested info
