### ISSUE TITLE
Azure CLI MsTeamsChannel failure

### ISSUE THREAD

**Issue by Earelith** [microsoft/botframework-sdk#6432]
Hello, not sure if this is a bug or an improper use of Azure CLI.
This is my first time using this tool. 
I need to automate Azure bot creation, especially the channel registration part. 
After failing using powershell, I'm also stumbling here.

Regards,

## Version
What package version of the SDK are you using.

azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\YYY\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

## Describe the bug
Give a clear and concise description of what the bug is.

The command az bot msteams create fails with "Error occurred in sending request"

## To Reproduce
cli.knack.cli: Command arguments: ['bot', 'msteams', 'create', '--resource-group', 'XXXPREPROD_group', '--name', 'Office_A_HANDLE', '--enable-calling', 'true', '--calling-web-hook', 'https://preprod.XXX.cloud:8544/callback/call', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01DB5100>, <function OutputProducer.on_global_arguments at 0x01F1FF58>, <function CLIQuery.on_global_arguments at 0x01F47B68>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'bot': ['azure.cli.command_modules.botservice']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: botservice                0.008        12        42
cli.azure.cli.core: Total (1)                 0.008        12        42
cli.azure.cli.core: Loaded 12 groups, 42 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : bot msteams create
cli.azure.cli.core: Command table: bot msteams create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03ACFF58>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\YYY\.azure\commands\2021-11-25.15-29-05.bot_msteams_create.2956.log'.
az_command_data_logger: command args: bot msteams create --resource-group {} --name {} --enable-calling {} --calling-web-hook {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03B17538>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x03B28C40>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03B28C88>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03B28D18>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01F1FFA0>, <function CLIQuery.handle_query_parameter at 0x01F47BB0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03B17610>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03B28CD0>]
Command group 'bot msteams' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=AzureBotService
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /{TenantId}/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/{TenantId}/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{TenantId}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/{TenantId}/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': '0af1a904-4dfc-11ec-b7ba-0028f8bdd090'
cli.azure.cli.core.commands.client_factory:     'CommandName': 'bot msteams create'
cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--resource-group --name --enable-calling --calling-web-hook --debug'
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 9e72c085-3d67-4eb3-94e6-9bdc2c954945
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Content-Length': '199'
msrest.http_logger:     'User-Agent': 'python/3.8.9 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3 azure-mgmt-botservice/0.3.0 Azure-SDK-For-Python AZURECLI/2.30.0 (MSI)'
msrest.http_logger: Request body:
msrest.http_logger: {"location": "global", "properties": {"channelName": "MsTeamsChannel", "properties": {"enableCalling": true, "callingWebHook": "https://preprod.XXX.cloud:8544/callback/call", "isEnabled": true}}}
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 HTTP/1.1" 500 7157
urllib3.util.retry: Incremented Retry for (url='/subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02'): Retry(total=3, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool: Retry: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02'): Retry(total=2, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool: Retry: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 HTTP/1.1" 500 7157
urllib3.util.retry: Incremented Retry for (url='/subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02'): Retry(total=1, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool: Retry: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 HTTP/1.1" 500 7157
urllib3.util.retry: Incremented Retry for (url='/subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02'): Retry(total=0, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool: Retry: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 HTTP/1.1" 500 7157
msrest.exceptions: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 (Caused by ResponseError('too many 500 error responses'))
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 846, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 846, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 846, in urlopen
  [Previous line repeated 1 more time]
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 836, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/universal_http/requests.py", line 139, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 507, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/botservice/channel_operations.py", line 80, in msteams_create
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/botservice/channel_operations.py", line 18, in create_channel
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/botservice/operations/_channels_operations.py", line 99, in create
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/service_client.py", line 336, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/__init__.py", line 197, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/__init__.py", line 150, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/requests.py", line 72, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/requests.py", line 137, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/__init__.py", line 150, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/requests.py", line 193, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/universal_http/requests.py", line 333, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/universal_http/requests.py", line 145, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/universal_http/requests.py", line 139, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 507, in send
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2b4b7d84-c7ed-475b-917a-582d5d94ed06/resourceGroups/XXXPREPROD_group/providers/Microsoft.BotService/botServices/Office_A_HANDLE/channels/MsTeamsChannel?api-version=2020-06-02 (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/botservice/_exception_handler.py", line 25, in bot_exception_handler
knack.util.CLIError: Error occurred in sending request. Please file an issue on https://github.com/microsoft/botframework-sdk

## Expected behavior
Wanted to add a channel registration (MS TEAMS) to bot Office_A_HANDLE

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by Earelith** [comment]
Well, I found the issue. After creating the bot with powershell, the bot type was flagged "Azure Bot". 
In order for the command to run successfully, the bot type hast to be "Bot Channels Registration".

I close this ticket, all is working fine.

Regards,
