### ISSUE TITLE
Bot framework REST API calls getting timeouts

### ISSUE THREAD

**Issue by penguinsource** [microsoft/botframework-sdk#6601]
## Describe the bug
I am sending POST requests to `https://smba.trafficmanager.net/amer` and receiving timeouts on my remote server (google cloud, app engine) - the same is not happening locally when using ngrok.

Nothing has changed on our code's behalf and it all started failing yesterday (June 14th).

## Expected behavior
Our platform proactively sends messages to an existing conversation (through the REST url) and then continues the conversation through a `bot-builder` implementation.

## Screenshots
<img width="1391" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/2596623/68e4e28e-7ec6-40b3-85a8-858c8860ff47">
<img width="1427" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/2596623/8dbe0fde-9d61-4155-8ed7-7c77a64fe7d0">

## Additional context
- Issue does not occur in ngrok, but it does occur on app engine instances
- Bot has been working fine for the past 2 years, but all of a sudden, something must have happened and it's now getting all these timeouts

```
 error: FetchError: request to https://smba.trafficmanager.net/amer/v3/conversations/a:17cILmBogFKvwOhSb3Qb8s8s8Mvi8-v28V74WaXT2do5qpcvX2iWx7u9TIFKgjUZCbC2Sbuy3LltGjgAxKHPhYDjwOaEarjchGEhQOtN2Rax4hMDG8YjSjl_rpBR-2yaD/activities/ failed, reason: connect ETIMEDOUT 52.114.142.186:443
      at ClientRequest.<anonymous> (/workspace/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (events.js:400:28)
      at TLSSocket.socketErrorListener (_http_client.js:475:9)
      at TLSSocket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT'
  },
```

**Comment by dmvtech** [comment]
Hi @penguinsource What channel(s) is this bot using? Teams, Direct Line, etc?

**Comment by penguinsource** [comment]
hey @dmvtech , this is using MS Teams

**Comment by tracyboehrer** [comment]
This is old and perhaps no longer relevant.  However, this would be a Teams issue.

**Comment by pyramid-scheme-ceo** [comment]
@tracyboehrer would like this re-opened please or do you know where else that I should raise this issue? We are getting many failures at the moment (e.g. screenshot below just from the past couple of hours) which is stopping us from sending messages and affecting customers. Note that all these requests took 20+ seconds before eventually failing.

![image](https://github.com/microsoft/botframework-sdk/assets/22147620/e8775a6c-f503-4258-8b2b-2c57a49a2a1f)

**Comment by penguinsource** [comment]
Hello! This is still an issue and it is still happening every weekend and sometimes on weekdays as well (such as today). **the failure rate is very high.**

The error is still occuring at the smba.trafficmanager.net DNS.

I am going to attach the same responses I still receive which I received last year.

Specific error response:
<img width="2371" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/2596623/6742afb1-489d-4e95-855d-44acee830848">

Here is how often it has occured in the last 30 days:

<img width="2372" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/2596623/1cd2932b-5f98-4a56-941e-ee02edb3a394">

<img width="1116" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/2596623/d87c5593-111f-4422-82dd-922e14c72d46">

I have a case open, but not with the Teams team yet. How can we reach support for this issue?

Thanks,
Mihai

**Comment by penguinsource** [comment]
@tracyboehrer can you please reopen this issue and suggest a github repository to create a separate issue in? we need this here for awareness of how old the issue has occured for

**Comment by tracyboehrer** [comment]
@penguinsource I would start with the Teams AI SDK repo.  This isn't something BF SDK can address.
